name: 'Testim.IO CLI runner'
description: 'This action run testim.io tests'
author: AndyKIron

inputs:
  baseURL:
    description: 'Set base URL to run tests on'
    required: true
#  branchName:
#    description: 'Set branch name'
#    required: true
#    default: 'master'
#  parallelGrids:
#    description: 'Set parallel grid to run tests (1 - 32)'
#    required: false
#    default: '10'
#  label:
#    description: 'Set test label'
#    required: false
#    default: 'active'
#  enablePixelValidation:
#    description: 'Set skip pixel validation flag (true/false)'
#    required: false
#    default: 'true'
#  testPlan:
#    description: 'Set test plans name'
#    required: false
#    default: 'all'
  grid:
    description: 'Testim Grid'
    required: false
    default: 'Testim-grid'
  testimToken:
    required: true
  testimProject:
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.testimToken }}
    - ${{ inputs.testimProject }}
    - ${{ inputs.grid }}
    - ${{ inputs.baseURL }}

#    - ${{ inputs.label }}
#    - ${{ inputs.testPlan }}
#    - ${{ inputs.branchName }}
#    - ${{ inputs.parallelGrids }}
#    - ${{ inputs.enablePixelValidation }}
